### ISSUE TITLE
error: only helios/ cyTOF v3 files are supported

### ISSUE THREAD

**Issue by MayaCyTOFnewbie** [JimboMahoney/cytofclean#17] opened 2021-08-10 09:07 UTC
Hi,
I want to use cytofclean as part of  prybakowska/CytofPipeline1 [https://github.com/prybakowska/CytofPipeline1]

I get this error msg although I am using CyTOF v3 files. 

the files were normalized, cleaned and debarcoded with the above pipeline.

what is wrong?

**Comment by JimboMahoney** [comment] 2021-08-10 16:47
Hmm, that might be tricky to fix.

Here is what I'm doing to check the files:

```
if ("Event_length" %in% params$name == FALSE){
    tkmessageBox(title = "Error!",
                 message = "Only Helios / CyTOF v3 files are supported!", type = "ok")
}
```

i.e. I'm looking for the presence of "Event_length" in the parameters.

Maybe your pipeline is removing that or chaning the name somehow?

**Comment by MayaCyTOFnewbie** [comment] 2021-08-12 12:38
Hi!

thanks for the quick respond!

should I put the files in a flowset first? 

This is what I did:

```
# I loaded the debarcoded fcs files (from the pipeline) to a flow set
files <- list.files(file.path(debarcode_dir), 
                    pattern = "_debarcoded.fcs$", 
                    full.names = TRUE, recursive = T)

fs_barcoded = read.flowSet(files)

as.data.frame(colnames(fs_barcoded))

# I also loaded the raw files to a flowset
# define full pathway to the files 
files <- list.files(file.path(raw_data_dir), 
                    pattern = ".FCS$", 
                    full.names = T)

# load files to a flow set
fs = read.flowSet(files)

as.data.frame(colnames(fs))

```
It seems the name changed from event_length to length. is there a way to correct back?

here is the output: 

> as.data.frame(colnames(fs_barcoded))
> 1                   Time
> 2                 length
> 3                 Center
> 4                 Offset
> 5                  Width
> 6               Residual
> 7                Pd102Di
> 8                Rh103Di
> 9                Pd104Di
> 10               Pd105Di
> 11               Pd106Di
> 12               Pd108Di
> 13               Pd110Di
> 14               Cd112Di
> 15               In113Di
> 16               Cd114Di
> 17               In115Di
> 18               Cd116Di
> 19               La139Di
> 20               Ce140Di
> 21               Pr141Di
> 22               Nd142Di
> 23               Nd143Di
> 24               Nd144Di
> 25               Nd145Di
> 26               Nd146Di
> 27               Sm147Di
> 28               Nd148Di
> 29               Sm149Di
> 30               Nd150Di
> 31               Eu151Di
> 32               Sm152Di
> 33               Eu153Di
> 34               Sm154Di
> 35               Gd155Di
> 36               Gd156Di
> 37               Gd157Di
> 38               Gd158Di
> 39               Tb159Di
> 40               Gd160Di
> 41               Dy161Di
> 42               Dy162Di
> 43               Dy163Di
> 44               Dy164Di
> 45               Ho165Di
> 46               Er166Di
> 47               Er167Di
> 48               Er168Di
> 49               Tm169Di
> 50               Er170Di
> 51               Yb171Di
> 52               Yb172Di
> 53               Yb173Di
> 54               Yb174Di
> 55               Lu175Di
> 56               Yb176Di
> 57             BCKG190Di
> 58               Ir191Di
> 59               Ir193Di
>  
> 
> as.data.frame(colnames(fs))
>    colnames(fs)
> 1          Time
> 2  Event_length
> 3       Pd102Di
> 4       Rh103Di
> 5       Pd104Di
> 6       Pd105Di
> 7       Pd106Di
> 8       Pd108Di
> 9       Pd110Di
> 10      Cd112Di
> 11      In113Di
> 12      Cd114Di
> 13      In115Di
> 14      Cd116Di
> 15      La139Di
> 16      Ce140Di
> 17      Pr141Di
> 18      Nd142Di
> 19      Nd143Di
> 20      Nd144Di
> 21      Nd145Di
> 22      Nd146Di
> 23      Sm147Di
> 24      Nd148Di
> 25      Sm149Di
> 26      Nd150Di
> 27      Eu151Di
> 28      Sm152Di
> 29      Eu153Di
> 30      Sm154Di
> 31      Gd155Di
> 32      Gd156Di
> 33      Gd157Di
> 34      Gd158Di
> 35      Tb159Di
> 36      Gd160Di
> 37      Dy161Di
> 38      Dy162Di
> 39      Dy163Di
> 40      Dy164Di
> 41      Ho165Di
> 42      Er166Di
> 43      Er167Di
> 44      Er168Di
> 45      Tm169Di
> 46      Er170Di
> 47      Yb171Di
> 48      Yb172Di
> 49      Yb173Di
> 50      Yb174Di
> 51      Lu175Di
> 52      Yb176Di
> 53    BCKG190Di
> 54      Ir191Di
> 55      Ir193Di
> 56       Center
> 57       Offset
> 58        Width
> 59     Residual
>

**Comment by JimboMahoney** [comment] 2021-08-12 15:16
Yup, the problem is the parameter name.

I might be able to change how the code checks for Helios files and uses the presence of the Guassian parameters instead...

I'll update this if/when I get around to that...

**Comment by JimboMahoney** [comment] 2021-08-12 15:21
OK, code updated. 

Hopefully it works as I can't test!

**Comment by MayaCyTOFnewbie** [comment] 2021-08-15 07:20
Hi,

So I should update package?

thanks!

Maya

**Comment by JimboMahoney** [comment] 2021-08-16 06:49
Yes I think if you install the package again it will see there is a newer version?

**Comment by MayaCyTOFnewbie** [comment] 2021-08-16 12:40
Hi

I update the version, now I get a new error:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'exprs': 'Event_length' is not a valid parameter in this flowFrame
Subscript out of bounds

thank you for all the help


from session info
cytofclean   * 1.0.3   2021-08-16 [1] Github (JimboMahoney/cytofclean@8375a5a)

**Comment by JimboMahoney** [comment] 2021-08-16 13:08
Hmm, it may be that CytofClean doesn't work with flowframes.

I've only ever used it / intended it to be used with fcs files.

**Comment by MayaCyTOFnewbie** [comment] 2021-08-17 06:35
Hi,

I did use it with FCS files.

I used the code above to check the panel (col.names). This is the only way I know how

**Comment by JimboMahoney** [comment] 2021-08-17 15:14
Hmm, OK well I've looked at the code and it's looking for "Event_length" a LOT.

Either I change my code to allow for both "Event_length" AND "length" or you change your code to rename "length" to "Event_length".

Not sure when I will get around to doing that! As I said, I'm afraid I don't work with mass/flow files any more!

**Comment by MayaCyTOFnewbie** [comment] 2021-09-12 13:59
Hi Jimbo!

I managed to correct for there error! yey! I change the name from "length" back to "Event_length", and then everything worked great!

However, when I look at the output figure, I see that it also cleans the data according to  "Yb172Di" channel. why? Can I cancel it somehow?

Many many thanks! I know you are not in the field anymore...

**Comment by JimboMahoney** [comment] 2021-09-12 14:39
Wow, that's weird (Re: Yb172Di channel).

I can't immediately see anything in the code that would cause that.

It's only looking for the Gaussian parameters (Width, Offset, Center and Residual) and optionally removing the beads selected by the user from the list 140Ce, 142Ce, 151Eu, 153Eu, 165Ho, 175Lu and 176Lu.

1) Are you selecting to remove bead channels when asked?
2) If so, which channels?

**Comment by MayaCyTOFnewbie** [comment] 2021-09-13 08:21
Hi,

So, actually, when I get to the step of removing beads I get this message:
![image](https://user-images.githubusercontent.com/77662582/133037466-4d9926c6-5828-4ee4-9d12-b4792060a1b4.png)

There is nothing to select. I think that the beads are removed during the normalization step (earlier in the pipeline). 

I ran the program again without beads removal, and this graph is not created.

thanks again!

Maya

**Comment by JimboMahoney** [comment] 2021-09-15 05:57
OK, sounds good! I'll close this issue now.

**Closed as completed by JimboMahoney** 2021-09-15 05:57 UTC
